### ISSUE TITLE
error: ‘BPF_NETFILTER’ - build bpfilter in Ubuntu 22 and enable the hadware enablement (HWE) stack.

### ISSUE THREAD

**Issue by tantm3** [facebook/bpfilter#82]
Hi everyone,

I am trying to build bpfilter in my current infrastructure which uses the Ubuntu 22.04 OS.
I enabled the HWE and upgraded the kernel to version 6.5, but there is an error when I hit `make -C $BUILD_DIR` for building the bpfilter. Here are some information:
```
## Upgrade kernal
sudo apt-get install --install-recommends linux-generic-hwe-22.04
root@com-glb-168:~/bpfilter# uname -r
6.5.0-45-generic
```

```
## Error log from make output
root@com-glb-168:~/bpfilter# make -C $BUILD_DIR
make: Entering directory '/root/bpfilter'
make[1]: Entering directory '/root/bpfilter'
make[2]: Entering directory '/root/bpfilter'
Consolidate compiler generated dependencies of target bpfilter
make[2]: Leaving directory '/root/bpfilter'
make[2]: Entering directory '/root/bpfilter'
[  1%] Building C object src/CMakeFiles/bpfilter.dir/core/bpf.c.o
/root/bpfilter/src/core/bpf.c: In function ‘bf_bpf_nf_link_create’:
/root/bpfilter/src/core/bpf.c:169:36: error: ‘BPF_NETFILTER’ undeclared (first use in this function); did you mean ‘IP_MSFILTER’?
  169 |     attr.link_create.attach_type = BPF_NETFILTER;
      |                                    ^~~~~~~~~~~~~
      |                                    IP_MSFILTER
/root/bpfilter/src/core/bpf.c:169:36: note: each undeclared identifier is reported only once for each function it appears in
/root/bpfilter/src/core/bpf.c:170:21: error: ‘struct <anonymous>’ has no member named ‘netfilter’
  170 |     attr.link_create.netfilter.pf = NFPROTO_IPV4;
      |                     ^
/root/bpfilter/src/core/bpf.c:171:21: error: ‘struct <anonymous>’ has no member named ‘netfilter’
  171 |     attr.link_create.netfilter.hooknum = bf_hook_to_nf_hook(hook);
      |                     ^
/root/bpfilter/src/core/bpf.c:172:21: error: ‘struct <anonymous>’ has no member named ‘netfilter’
  172 |     attr.link_create.netfilter.priority = priority;
      |                     ^
make[2]: *** [src/CMakeFiles/bpfilter.dir/build.make:104: src/CMakeFiles/bpfilter.dir/core/bpf.c.o] Error 1
make[2]: Leaving directory '/root/bpfilter'
make[1]: *** [CMakeFiles/Makefile2:237: src/CMakeFiles/bpfilter.dir/all] Error 2
make[1]: Leaving directory '/root/bpfilter'
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/root/bpfilter'
```

I think the error is related to `BPF_NETFILTER` kernel module, so do I need to do something to enable it?

**Comment by qdeslandes** [comment]
Hi @tantm3 

I had the same issue when trying to get CI up and ready for Ubuntu 22.04. The reason is the definition for `BPF_NETFILTER` is missing. Even though Ubuntu's HWE stack provides Linux 6.5 (and `BPF_NETFILTER` has been added in 6.4), the userspace headers provided by Ubuntu are not from Linux 6.5, but 5.15 (IIRC, which is the non-HWE kernel version). 

It's possible to install the headers for Linux 6.5, which will be located in `/usr/src/linux-headers-6.5.0-18-generic`, but those are not meant to be used for userspace application, such as `bpfilter`.

Hence, for the time being, I'm afraid `bpfilter` can't be build on Ubuntu 22.04, even with HWE enabled. I've updated the #84 documentation to clarify this.

This is slightly frustrating as the kernel running on Ubuntu 22.04 HWE could perfectly work with `bpfilter`, but it would require some work (extract required definitions from supported kernel, or rely on the BTF data from the kernel for example) and a lot of tests to ensure `bpfilter` works on 22.04 HWE and it's not the priority right now.
